---
title: "Phase I Report"
author: "Mia Isaacs"
date: "2025-02-08"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gtsummary)
library(nlme)
```

# import data

```{r}
data_clean =
  read_csv("~/Desktop/Pharm Stats/Lab Report 1/phase1_report/data/dta02.csv") |> 
  janitor::clean_names()
```

```{r}
test_drug <- data_clean |> 
  filter(drug == 1)
```

```{r}
ref_drug <- data_clean |> 
  filter(drug == 2)
```


# summary statistics by trt group

```{r}
geometric_mean <- function(x) {
  exp(mean(log(x[x > 0]), na.rm = TRUE))
}
```

**for new treatment**
```{r}
summary_stats1 <- test_drug |> 
  summarise(
    cmax_min = min(cmax, na.rm = TRUE),
    cmax_max = max(cmax, na.rm = TRUE),
    cmax_mean = mean(cmax, na.rm = TRUE),
    cmax_sd = sd(cmax, na.rm = TRUE),
    cmax_cv = (sd(cmax, na.rm = TRUE) / mean(cmax, na.rm = TRUE)) * 100,
    cmax_gmean = geometric_mean(cmax),
    
    auct_min = min(auct, na.rm = TRUE),
    auct_max = max(auct, na.rm = TRUE),
    auct_mean = mean(auct, na.rm = TRUE),
    auct_sd = sd(auct, na.rm = TRUE),
    auct_cv = (sd(auct, na.rm = TRUE) / mean(auct, na.rm = TRUE)) * 100,
    auct_gmean = geometric_mean(auct),
    
    aucinf_min = min(aucinf, na.rm = TRUE),
    aucinf_max = max(aucinf, na.rm = TRUE),
    aucinf_mean = mean(aucinf, na.rm = TRUE),
    aucinf_sd = sd(aucinf, na.rm = TRUE),
    aucinf_cv = (sd(aucinf, na.rm = TRUE) / mean(aucinf, na.rm = TRUE)) * 100,
    aucinf_gmean = geometric_mean(aucinf)
  ) |> 
  pivot_longer(cols = everything(), names_to = "stat", values_to = "value") |> 
  separate(stat, into = c("variable", "statistic"), sep = "_") |> 
  pivot_wider(names_from = "statistic", values_from = "value")
```

```{r, treat = 1}
summary_table1 <- summary_stats1 |> 
  select(variable, min, max, mean, sd, cv, gmean) |> 
  mutate(variable = case_when(
    variable == "cmax" ~ "**Cmax** (ng/mL)",
    variable == "auct" ~ "**AUCt** (ng路h/mL)",
    variable == "aucinf" ~ "**AUCinf** (ng路h/mL)"
  )) |> 
  rename(
    "Parameter" = variable,
    "Min" = min,
    "Max" = max,
    "Mean" = mean,
    "Std Dev" = sd,
    "CV (%)" = cv,
    "Geometric Mean" = gmean
  ) |> 
  gt() |> 
  gt::tab_header(title = md("**Treatment Summary Statistics for Cmax, AUCt, and AUCinf**")) |> 
  gt::fmt_number(columns = c("Min", "Max", "Mean", "Std Dev", "CV (%)", "Geometric Mean"), decimals = 2) |> 
  gt::fmt_markdown(columns = "Parameter") |> 
  gt::tab_style(
    style = list(gt::cell_fill(color = "#F2F2F2")),  # Light grey
    locations = gt::cells_body(rows = seq(1, nrow(summary_stats1), by = 2))
  ) |> 
  gt::opt_table_font(
    font = list(gt::google_font(name = "Garamond"))
  )

summary_table1
```

**for reference treatment**
```{r}
summary_stats2 <- ref_drug |> 
  summarise(
    cmax_min = min(cmax, na.rm = TRUE),
    cmax_max = max(cmax, na.rm = TRUE),
    cmax_mean = mean(cmax, na.rm = TRUE),
    cmax_sd = sd(cmax, na.rm = TRUE),
    cmax_cv = (sd(cmax, na.rm = TRUE) / mean(cmax, na.rm = TRUE)) * 100,
    cmax_gmean = geometric_mean(cmax),
    
    auct_min = min(auct, na.rm = TRUE),
    auct_max = max(auct, na.rm = TRUE),
    auct_mean = mean(auct, na.rm = TRUE),
    auct_sd = sd(auct, na.rm = TRUE),
    auct_cv = (sd(auct, na.rm = TRUE) / mean(auct, na.rm = TRUE)) * 100,
    auct_gmean = geometric_mean(auct),
    
    aucinf_min = min(aucinf, na.rm = TRUE),
    aucinf_max = max(aucinf, na.rm = TRUE),
    aucinf_mean = mean(aucinf, na.rm = TRUE),
    aucinf_sd = sd(aucinf, na.rm = TRUE),
    aucinf_cv = (sd(aucinf, na.rm = TRUE) / mean(aucinf, na.rm = TRUE)) * 100,
    aucinf_gmean = geometric_mean(aucinf)
  ) |> 
  pivot_longer(cols = everything(), names_to = "stat", values_to = "value") |> 
  separate(stat, into = c("variable", "statistic"), sep = "_") |> 
  pivot_wider(names_from = "statistic", values_from = "value")
```

```{r, treat = 2}
summary_table2 <- summary_stats2 |> 
  select(variable, min, max, mean, sd, cv, gmean) |> 
  mutate(variable = case_when(
    variable == "cmax" ~ "**Cmax** (ng/mL)",
    variable == "auct" ~ "**AUCt** (ng路h/mL)",
    variable == "aucinf" ~ "**AUCinf** (ng路h/mL)"
  )) |> 
  rename(
    "Parameter" = variable,
    "Min" = min,
    "Max" = max,
    "Mean" = mean,
    "Std Dev" = sd,
    "CV (%)" = cv,
    "Geometric Mean" = gmean
  ) |> 
  gt() |> 
  gt::tab_header(title = md("**Reference Summary Statistics for Cmax, AUCt, and AUCinf**")) |> 
  gt::fmt_number(columns = c("Min", "Max", "Mean", "Std Dev", "CV (%)", "Geometric Mean"), decimals = 2) |> 
  gt::fmt_markdown(columns = "Parameter") |> 
  gt::tab_style(
    style = list(gt::cell_fill(color = "#F2F2F2")),  # Light grey
    locations = gt::cells_body(rows = seq(1, nrow(summary_stats1), by = 2))
  ) |> 
  gt::opt_table_font(
    font = list(gt::google_font(name = "Garamond"))
  )

summary_table2
```

# conducting ANOVA
```{r}
data_clean$subj <- as.factor(data_clean$subj)
data_clean$seq <- as.factor(data_clean$seq)
data_clean$period <- as.factor(data_clean$period)
data_clean$drug <- as.factor(data_clean$drug)

model <- lme(cmax ~ seq + period + drug, 
             random = ~1 | subj, 
             data = data_clean)

summary(model)

anova(model)
```

**for cmax**
```{r}
result_cmax = lme(log(cmax) ~ seq + period + drug, random=~1|subj,data=data_clean) 
summary(result_cmax) 
VarCorr(result_cmax)              
ci_cmax = intervals(result_cmax, 0.90)
exp(ci_cmax$fixed["drug2",])
```

**for auct**
```{r}
result_auct = lme(log(auct) ~ seq + period + drug, random=~1|subj, data=data_clean)
summary(result_auct)
VarCorr(result_auct)
ci_auct = intervals(result_auct, 0.90)
exp(ci_auct$fixed["drug2",])
```

**for aucint**
```{r}
result_aucinf = lme(log(aucinf) ~ seq + period + drug, random=~1|subj, 
                    data=data_clean, na.action = na.omit)
summary(result_aucinf)
VarCorr(result_aucinf)
ci_aucinf = intervals(result_aucinf, 0.90)
exp(ci_aucinf$fixed["drug2",])
```

**make table**
```{r}
result_cmax = lme(log(cmax) ~ seq + period + drug, random=~1|subj, data=data_clean)
ci_cmax = intervals(result_cmax, level = 0.90)
log_est_cmax <- summary(result_cmax)$tTable["drug2", "Value"]
grm_cmax <- exp(log_est_cmax)  
ci_cmax_values <- exp(ci_cmax$fixed["drug2", ])

result_auct = lme(log(auct) ~ seq + period + drug, random=~1|subj, data=data_clean)
ci_auct = intervals(result_auct, level = 0.90)
log_est_auct <- summary(result_auct)$tTable["drug2", "Value"]
grm_auct <- exp(log_est_auct)  
ci_auct_values <- exp(ci_auct$fixed["drug2", ])

result_aucinf = lme(log(aucinf) ~ seq + period + drug, random=~1|subj, 
                    data=data_clean, na.action = na.omit)
ci_aucinf = intervals(result_aucinf, level = 0.90)
log_est_aucinf <- summary(result_aucinf)$tTable["drug2", "Value"]
grm_aucinf <- exp(log_est_aucinf)  
ci_aucinf_values <- exp(ci_aucinf$fixed["drug2", ])

summary_table3 <- data.frame(
  Parameter = c("Cmax", "AUCt", "AUCinf"),
  Log_Estimate = c(log_est_cmax, log_est_auct, log_est_aucinf),
  GRM_Ratio = c(grm_cmax, grm_auct, grm_aucinf),
  CI_Lower_90 = c(ci_cmax_values[1], ci_auct_values[1], ci_aucinf_values[1]),
  CI_Upper_90 = c(ci_cmax_values[2], ci_auct_values[2], ci_aucinf_values[2])
) |>
rename(
    "Log Estimate" = Log_Estimate,
    "GM Ratio" = GRM_Ratio,
    "90% CI Lower" = CI_Lower_90,
    "90% CI Upper" = CI_Upper_90,
  )

summary_table3 |> 
  gt() |> 
  gt::tab_header(title = md("**Geometric Mean Ratios Comparing Treatment to Reference**")) |> 
  gt::fmt_number(columns = c("Log Estimate", "GM Ratio", "90% CI Lower", "90% CI Upper"), decimals = 2) |> 
  gt::fmt_markdown(columns = "Parameter") |> 
    gt::tab_style(
    style = list(gt::cell_fill(color = "#F2F2F2")),  # Light grey
    locations = gt::cells_body(rows = seq(1, nrow(summary_stats1), by = 2))
  ) |> 
  gt::opt_table_font(
    font = list(gt::google_font(name = "Garamond"))
  ) |> 
  gt::tab_style(
    style = list(gt::cell_text(weight = "bold")),
    locations = gt::cells_body(columns = "Parameter")
  )
```

